### ISSUE TITLE
Problema con la Resolución de la Máquina Virtual

### ISSUE THREAD

**Issue by jorgecabreracruz** [AgoraUS-G2-1617/G26#1]
Al abrir la Máquina Virtual con la que vamos a trabajar en la asignatura, observamos como la resolución no es la más adecuada para escribir código El motivo es porque no usa la pantalla completa, tal y como podemos observar en la captura
![captura 01](https://cloud.githubusercontent.com/assets/22940968/20190421/a3920496-a781-11e6-9701-23e1bd45677b.PNG)

**Comment by CeuxDruman** [comment]
Hemos encontrado una solución:

1- Con la máquina virtual abierta, accedemos al menu "Dispositivos" de virtual box y elegimos la opción "Insertar imagen de CD de las <Guest Additions>...
![zzz13](https://cloud.githubusercontent.com/assets/11983593/20190784/1e549a12-a783-11e6-976a-ec5496fffde4.png)

Virtual Box realizará una serie de operaciones automáticas.

**Esto podría bastar para solucionar el error.**

Sin embargo, si no lo solucionar continúa con los siguientes pasos:

2- Selecciona el icono del CD del menu lateral izquierdo.
![zzz14](https://cloud.githubusercontent.com/assets/11983593/20190842/5e796276-a783-11e6-905a-b6fb264f90f6.png)

3- Haz clic en el botón "Ejecutar programa".
![zzz15](https://cloud.githubusercontent.com/assets/11983593/20190856/65c646f2-a783-11e6-9205-ccdcadba7d4e.png)

Se abrirá una terminal en la que se realizarán automáticamente una serie de operaciones.
![zzz12](https://cloud.githubusercontent.com/assets/11983593/20190860/6d767d90-a783-11e6-8c06-403e7bcbc4b0.PNG)

Al acabar el problema estará resuelto.

4- Para aplicar los cambios reinicia la máquina virtual. Al abrirla de nuevo y cambiar el tamaño de la ventana, la máquina virtual se ajustará automáticamente.
![zzz16](https://cloud.githubusercontent.com/assets/11983593/20190875/77a64b9c-a783-11e6-89ff-022203383232.PNG)
