### ISSUE TITLE
Métodos de recuento no comentados

### ISSUE THREAD

**Issue by CeuxDruman** [AgoraUS-G2-1617/G26#10]
Lo métodos de recuento:
-D'hont
-Rangos de edad habituales
no han sido debidamente comentados, por lo que se requiere que sean comentados conforme a lo establecido con los otros métodos de recuento.

**Comment by josgirrui** [comment]
Se me había olvidado por completo, me pongo a hacerlo a ver cuanto tardo, según se me compliquen los tengo esta tarde o mañana. Voy a mirar el resto de los issues primero.

**Comment by CeuxDruman** [comment]
Sigue sin estar hecho, pero se cierra Issue por haberse comentado (deshabilitado) el código de ambos métodos.
