### ISSUE TITLE
Eliminación del código heredado

### ISSUE THREAD

**Issue by AlbertoAreLun** [AgoraUS-G2-1617/G26#11]
Debemos eliminar el código heredado que no vayamos a usar, ya que esta incompleto y hace que no se pueda hacer la build del proyecto.

![image](https://cloud.githubusercontent.com/assets/22639259/21741009/871b4c7a-d4ca-11e6-85ea-933327047225.png)

**Comment by CeuxDruman** [comment]
Se ha resuelto la situación en la rama Eliminacion-codigo-heredado y los cambios han sido transferidos a la rama de Desarrollo mediante el Pull Request #19 .
