### ISSUE TITLE
Eliminación del código heredado - Controllers

### ISSUE THREAD

**Issue by AlbertoAreLun** [AgoraUS-G2-1617/G26#13]
Eliminación de BaseController, y en ApiController eliminar el extends de BaseController y todo el contenido **hasta** /test sin incluir, de la carpeta "counting/src/main/java/es/us/agoraus/counting/controllers"

**¡ATENCIÓN!: Este es un análisis a primera vista de lo que entendemos que se puede eliminar sin problema, pero con la eliminación de cada archivo y/o contenido se debe probar:
-Que funcionen todos los test JUnit de CountingTest.
De no ser así comprobad qué habéis borrado y qué deberíais mantener, dejando constancia de ello en el Issue de GitHub destinado a la eliminación de código heredado**

**Comment by josgirrui** [comment]
efd7bfac3eb4312bb9f55823233104e66126f0ec. Borrado el código sobrante.

**Comment by AlbertoAreLun** [comment]
Revisado y comprobado
