### ISSUE TITLE
Eliminación del código heredado - Dto

### ISSUE THREAD

**Issue by AlbertoAreLun** [AgoraUS-G2-1617/G26#14]
En la carpeta "counting/src/main/java/es/us/agoraus/counting/dto" eliminar todo menos **Status** y **Vote**.

**¡ATENCIÓN!: Este es un análisis a primera vista de lo que entendemos que se puede eliminar sin problema, pero con la eliminación de cada archivo y/o contenido se debe probar:
-Que funcionen todos los test JUnit de CountingTest.
De no ser así comprobad qué habéis borrado y qué deberíais mantener, dejando constancia de ello en el Issue de GitHub destinado a la eliminación de código heredado**

**Comment by jorgecabreracruz** [comment]
890defab645556596396548c308c07ce4b3dcb6f. 
He borrado la parte de código innecesaria.

**Comment by AlbertoAreLun** [comment]
Revisado y comprobado
