### ISSUE TITLE
Eliminación del código heredado - Test unit CountingTest

### ISSUE THREAD

**Issue by AlbertoAreLun** [AgoraUS-G2-1617/G26#15]
Eliminación de las primeras lineas comentadas del test "CountingTest" de la carpeta "counting/src/test/java/es/us/agoraus/counting/unit/".

**¡ATENCIÓN!: Este es un análisis a primera vista de lo que entendemos que se puede eliminar sin problema, pero con la eliminación de cada archivo y/o contenido se debe probar:
-Que funcionen todos los test JUnit de CountingTest.
De no ser así comprobad qué habéis borrado y qué deberíais mantener, dejando constancia de ello en el Issue de GitHub destinado a la eliminación de código heredado**

**Comment by jorgecabreracruz** [comment]
d91d9a8ede44dbe9423a0407c52ceb0720e5d512
Ya lo he solucionado. Era eliminar las líneas de código innecesarias.

**Comment by AlbertoAreLun** [comment]
Revisado y comprobado
