### ISSUE TITLE
Eliminación del código heredado - Views

### ISSUE THREAD

**Issue by AlbertoAreLun** [AgoraUS-G2-1617/G26#16]
Eliminación de las vistas  "non-segmented-charts.jsp" y "segmented-charts.jsp" de la carpeta "counting/src/main/webapp/WEB-INF/views".

**¡ATENCIÓN!: Este es un análisis a primera vista de lo que entendemos que se puede eliminar sin problema, pero con la eliminación de cada archivo y/o contenido se debe probar:
-Que funcionen todos los test JUnit de CountingTest.
De no ser así comprobad qué habéis borrado y qué deberíais mantener, dejando constancia de ello en el Issue de GitHub destinado a la eliminación de código heredado**

**Comment by josgirrui** [comment]
b92f6210e70a387d7b06abb65e45546599ebd570 eliminadas ambas vistas.

**Comment by josgirrui** [comment]
b92f6210e70a387d7b06abb65e45546599ebd570 Eliminadas ambas vistas.

**Comment by AlbertoAreLun** [comment]
Revisado y comprobado
