### ISSUE TITLE
Tests incorrectos y sin realizar

### ISSUE THREAD

**Issue by CeuxDruman** [AgoraUS-G2-1617/G26#18]
### Tests incorrectos
Los tests "testCocienteDroop", "testMetodoSainteLague" y "testMetodoDHont" no comprueban nada, simplemente ejecutan e imprimer el resultado por pantalla.

Tal y como en el resto de tests, cada test debería comprobar no solo que no se produce ninguna excepción, si no que el resultado es exactamente el esperado y no otro mediante Asserts.

### Tests sin realizar
Falta por realizar los test correspondientes al método de recuento por rangos de edad habituales.

**Comment by josgirrui** [comment]
773e2c29ef9e2ff8b6b8fe55d832c640d5fc6509 Hecho.

**Comment by CeuxDruman** [comment]
Revisado y comprobado.
