### ISSUE TITLE
Errores con la dependencia del subsistema de Verificación

### ISSUE THREAD

**Issue by CeuxDruman** [AgoraUS-G2-1617/G26#2]
Tras actualizar Maven hay una dependencia, concretamente la del subsistema de verificación, que no es capaz de descargar ya que está corrupta/enlace roto/servidor caído/etc... Dan la cara 3 errores y 1 warning:

![image](https://cloud.githubusercontent.com/assets/11983593/20199933/4aa27b36-a7ae-11e6-8d37-a989f7f16b86.png)

**Comment by AlbertoAreLun** [comment]
Esta configurado para que se baje de un repositorio el cual está caído, por lo tanto el jar que descarga maven al actualizar es un jar vacío/corrupto. Descargando el proyecto verificación y convirtiéndolo a jar, o consiguiendo el jar y introduciéndolo manualmente deberia de solucionarse.

**Comment by CeuxDruman** [comment]
Uno de los errores finalmente no está relacionado con ésta incidencia, se ha solucionado en el Issue #3.

**Comment by guillermo-ag-95** [comment]
Para arreglar los dos fallos pertenecientes al .jar del sistema de verificación, hemos tenido que tomar el proyecto de Verificación del año pasado, arreglar los fallos que éste presentaba y generar un nuevo .jar. Este .jar se ha añadido al repositorio.

Para desplegar el proyecto, hemos cambiado el servidor Tomcat a Pivotal tc Server Developer y desde el navegador de la máquina virtual, se introduce la url localhost:8080/counting/

**Comment by CeuxDruman** [comment]
@guillermo-ag-95 añade un poco más de información como el enlace del que habéis sacado el .jar, qué cosas habéis arreglado del mismo, cómo "añadirlo al repositorio"...

Nosotros obviamos esa información porque la conocemos y la tenemos reciente. Pero para la documentación hará falta un mayor nivel de detalle, sólo con explicarle eso a la persona que le salga el problema por primera vez no sería suficiente para que lo resolviese sin problemas.

**Comment by CeuxDruman** [comment]
77c607b1759988d63912a969227df05070fe93a4

**Comment by CeuxDruman** [comment]
Este error queda descartado al desechar la mayor parte del código existente y, por lo tanto, no requerir este sistema de Verificación.
