### ISSUE TITLE
Faltan los tipos de recuento por escaños "Cociente Droop" y "Método Sainte-Laguë"

### ISSUE THREAD

**Issue by CeuxDruman** [AgoraUS-G2-1617/G26#6]
Faltan por realizar los recuentos por escaños:
-Cociente Droop
-Método Sainte-Laguë

¿Hay algún problema con ellos? ¿Para cuándo podrían estar hechos?

**Comment by josgirrui** [comment]
039d04991e1546b995df522ef9bcc7d230d4b549 y e28ec6164e47bfd7ba9445f72d050a1c16026cd6 . Ya están testeados y funcionando todos los métodos.

**Comment by CeuxDruman** [comment]
Revisado y comprobado.
