### ISSUE TITLE
Nombre de recuento incorrecto

### ISSUE THREAD

**Issue by CeuxDruman** [AgoraUS-G2-1617/G26#8]
Para el recuento por rangos de edad habituales se ha establecido un nombre de método incorrecto "rangeAge", que:
1. No sigue el estándar establecido por el que debe acabar en "Count".
2. No distingue al método respecto al recuento por rango de edades dado ("ageRangeCount").

Esto resulta en la dificultad a la hora de entender y usar el código tanto por nosotros como para los que lo usen el año que viene.

Por lo que debe ser cambiado a, por ejemplo, "usualAgeRanges".

**Comment by josgirrui** [comment]
Cambio hecho.

**Comment by josgirrui** [comment]
Corregido en 8a9f96fdb3c7eed470371e56377de76a8ab241b1.

**Comment by CeuxDruman** [comment]
Tienes una errata, has puesto "usalAgeRanges" en vez de "usualAgeRanges".

**Comment by josgirrui** [comment]
7bc94468105e66eb60081546ec7cce9802deae58 arreglado.

**Comment by CeuxDruman** [comment]
Revisado. Los métodos de recuento "usualAgeRanges" y "metodoSainteLague" deben acabar en "Count" como el resto.

**Comment by CeuxDruman** [comment]
Cuando lo corrijas, comprueba también que los nombres de los tests concuerden.

**Comment by josgirrui** [comment]
070f54e34778d4e44d43aa78a612d5e6d2d6c578. Esperemos que esta vez ya esté.

**Comment by CeuxDruman** [comment]
Revisado y comprobado.
