### ISSUE TITLE
Formato de salida incorrecto en el recuento por rangos de edad habituales

### ISSUE THREAD

**Issue by CeuxDruman** [AgoraUS-G2-1617/G26#9]
El formato de salida no concuerda con el establecido, ya que:
1. Inserta espacios innecesarios entre los distintos recuentos de cada voto.
2. Utiliza ":" en vez de "=".
3. Presenta caracteres incorrectos que también dificultarán o harán imposible el procesado del recuento por parte de los distintos subsistemas como "[", "-", y ")" entre los nombres de los distintos recuentos para cada voto. Por ejemplo, se debería cambiar "numberOfVotes[30-45)" por "numberOfVotes30To45".
4. No respeta el estándar establecido para el nombrado de los distintos recuentos para cada voto, por el cual debe comenzar por "count" seguido del recuento que corresponda. Por ejemplo, se debería cambiar "numberOfVotes30To45" por "count30To45".

**Comment by josgirrui** [comment]
Corregido.`string.add("id=" + id + ";countUnder30=" + mapa.get(id)[0] + ";count30to45="
					+ mapa.get(id)[1] + ";count45to60=" + mapa.get(id)[2] + ";count60to75="
					+ mapa.get(id)[3] + ";countOver75=" + mapa.get(id)[4]);`

**Comment by josgirrui** [comment]
Corregido. La cadena de texto se genera de la siguiente manera:
string.add("id=" + id + ";countUnder30=" + mapa.get(id)[0] + ";count30to45=" + mapa.get(id)[1] + ";count45to60=" + mapa.get(id)[2] + ";count60to75=" + mapa.get(id)[3] + ";countOver75=" + mapa.get(id)[4]);
8a9f96fdb3c7eed470371e56377de76a8ab241b1

**Comment by CeuxDruman** [comment]
Revisado y comprobado.
